apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-app
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: enkelejd/node-app:v1 # Use the provided Docker image
          ports:
            - containerPort: 4000 # Make sure this is the correct port your app listens on
          env:
            - name: PORT
              value: "4000"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
