apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000 # The port exposed by the service
      targetPort: 3000 # The port the app is running on inside the container
  type: ClusterIP # You can use LoadBalancer or ClusterIP depending on your use case
